language: python

python:
  - 2.7

install:
  - pip install codecov pytest pytest-cov flake8 pep8
  - pip install -e .

script:
  - pep8 --exclude=tests .
  - flake8 --exclude=tests .
  - py.test

after_success:
  - codecov
